# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Standard action you need to include in your workflow.
      # This action will give your workflow a local copy of your repo.
      #
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file my-app/pom.xml
    - name: Publish
      run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
